### ISSUE TITLE
Can't use bulleted list in config.yaml

### ISSUE THREAD

**Issue by ali1234** [ogra1/packageproxy#1]
If config.yaml is really yaml I should be able to write this:

```
config:
  packageproxy:
    repos:
      - [ubuntu,http://archive.ubuntu.com/ubuntu]
      - [ubuntu-ports,http://ports.ubuntu.com/ubuntu-ports]
    ...
```

However it does not work. The repos are dropped from the config when the service is restarted.
